# Generated by Django 3.2.7 on 2022-01-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='shareDrive',
        ),
        migrations.AddField(
            model_name='checkout',
            name='oderstatus',
            field=models.CharField(choices=[('unfinished', 'Chưa hoàn thành'), ('finished', 'Hoàn thành')], default='', max_length=20, verbose_name='Trạng thái đơn hàng'),
        ),
        migrations.AddField(
            model_name='checkout_email',
            name='oderstatus',
            field=models.CharField(choices=[('unfinished', 'Chưa hoàn thành'), ('finished', 'Hoàn thành')], default='', max_length=20, verbose_name='Trạng thái đơn hàng'),
        ),
        migrations.AlterField(
            model_name='emailbusiness',
            name='shareDrive',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Drive nhóm'),
        ),
    ]
