# Generated by Django 3.2.7 on 2022-01-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
