# Generated by Django 3.2.7 on 2022-01-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenho', models.CharField(max_length=50, null=True, verbose_name='Họ tên: ')),
            ],
        ),
    ]
