# Generated by Django 3.2.7 on 2022-01-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
