# Generated by Django 4.0 on 2021-12-28 12:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Tiêu đề')),
                ('date', models.DateTimeField(verbose_name='ngày đăng')),
                ('avata', models.ImageField(upload_to='', verbose_name='ảnh đại chủ đề')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Nội dung')),
            ],
            options={
                'db_table': 'article',
                'ordering': ['-id'],
            },
        ),
    ]
