# Generated by Django 3.2.7 on 2022-01-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramFeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(default='Ảnh instagram', max_length=100, verbose_name='Note')),
                ('image', models.ImageField(upload_to='', verbose_name='ảnh instagram feeds')),
            ],
        ),
    ]
