# Generated by Django 3.2.7 on 2022-01-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
