# Generated by Django 3.2.7 on 2022-01-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='heroDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='tiêu đề hero')),
                ('subTitle', models.CharField(max_length=100, verbose_name='tiêu đề nhỏ')),
                ('content', models.CharField(max_length=200, verbose_name='nội dung here')),
            ],
            options={
                'db_table': 'Demo Hero',
            },
        ),
    ]
