# Generated by Django 4.0 on 2021-12-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocompany',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Thành phố / Tỉnh'),
        ),
    ]
