# Generated by Django 3.2.7 on 2022-01-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullName',
            field=models.CharField(default='', max_length=30, verbose_name='Họ Và tên'),
        ),
    ]
